version: "3.8"

services:
  django:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  celery:
    build: .
    container_name: celery
    command: celery -A core worker -l INFO
    volumes:
      - .:/usr/src/app/
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - django
      - redis

  celery_beat:
    build: .
    container_name: celery_beat
    command: celery -A core beat -l INFO -S django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/usr/src/app/
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - django
      - celery

  redis:
    image: "redis:alpine"
    container_name: redis
