# Generated by Django 3.2.25 on 2024-06-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=2042, null=True, verbose_name='Nome ')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Quantidade ')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo: ')),
            ],
            options={
                'db_table': 'produtos',
            },
        ),
    ]
