# Generated by Django 3.2.25 on 2024-07-14 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0018_improve_crontab_helptext'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarefaExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('caminho_modulo', models.CharField(max_length=255)),
                ('nome_modulo', models.CharField(max_length=255)),
                ('nome_funcao', models.CharField(max_length=255)),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.crontabschedule')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
